// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using MonoTouch.Dialog.Utilities;

namespace CollectionViewAttempt
{
	public partial class FeaturedArticlesCell : UICollectionViewCell, IImageUpdated
	{
		public static readonly NSString Key = new NSString ("FeaturedArticlesCell");

		UIImageView imageView;

		[Export ("initWithFrame:")]
		public FeaturedArticlesCell (RectangleF frame) : base (frame)
		{
			// TODO: add subviews to the ContentView, set various colors, etc.
			imageView = new UIImageView (new RectangleF (0, 0, 200, 200));
			imageView.ContentMode = UIViewContentMode.ScaleAspectFit;
			ContentView.AddSubview (imageView);
		}

		public void UpdateCell (Uri uri)
		{
			imageView.Image = ImageLoader.DefaultRequestImage (uri, this);
		}

		public void UpdatedImage (Uri uri)
		{
			imageView.Image = ImageLoader.DefaultRequestImage (uri, this);
		}
	}
}
